### ISSUE TITLE
[Bug Report] UI issues when using Chromium based browser (Microsoft Edge)

### ISSUE THREAD

**Issue by remlei** [SelfhostedPro/Yacht#419]
**Describe the bug**
The UI basically stops working. For example viewing logs will result blank, going to Settings >> Templates shows empty settings (as if there's no templates where set) last but not the least, deploying new containers will basically do nothing. Templates section is also empty.

**To Reproduce**
This issue sometimes pops-up on its own without doing anything special (deploying containers, viewing the containers status etc...) but the most reliable one to trigger is this:
1. Go to 'Setting'
2. Click on 'Update Tab'
3. There some sort of progress bar animation going from left to right, this will not end.
4. Now you can browse any part that I mention before.

**Screenshots**
![Web capture_13-7-2021_81531_192 168 254 2](https://user-images.githubusercontent.com/9265995/125371099-9e08e900-e3b2-11eb-84ba-afe6f4cb6d65.jpeg)
![Web capture_13-7-2021_8150_192 168 254 2](https://user-images.githubusercontent.com/9265995/125371102-9f3a1600-e3b2-11eb-930b-45620744062c.jpeg)
![Web capture_13-7-2021_81356_192 168 254 2](https://user-images.githubusercontent.com/9265995/125371103-9f3a1600-e3b2-11eb-87a3-cdbc579cca6b.jpeg)
![Web capture_13-7-2021_81331_192 168 254 2](https://user-images.githubusercontent.com/9265995/125371104-9fd2ac80-e3b2-11eb-91b9-45f0c67549b8.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 10 / Ubuntu 21.02
 - Browser: MS Edge/Brave
 - Yacht Version v0.0.7-alpha-2021-05-31--16

**Comment by permag02** [comment]
Can confirm I also have this issue:
 Yacht .7 alpha
Chrome 92 - Windows 10

I can see it fine on Firefox 90 tho

**Comment by jnewman33** [comment]
FWIW I am seeing same issue as well with Chrome 92 on Win 11

**Comment by skluthe** [comment]
Sorry I haven’t got around to digging in more yet. I’m thinking of lowering the refresh time by default and adding a drop down to select refresh times which should help quite a bit.

**Comment by remlei** [comment]
I can also say that using Firefox kinda fix the issue. Though sometimes it still have some sort of issue (eg not responding) but a simple refresh on the webpage is more than enough to fix it.

so for now, Chromium based Browser is not usable for Yacht. While Firefox works well enough.

**Comment by wickedyoda** [comment]
@remlei @jnewman33 @permag02 Can yall check this out again and let me know if your still having issues, I have yacht hosted both on an AMD64 VM and arm64 raspberry pi 4. Both I am able to get loaded with google chrome and chromium browsers.
![Screenshot 2021-11-23 163839](https://user-images.githubusercontent.com/68271168/143140261-534d8aef-cd37-45a5-8c41-9d2b5eea18d5.png)

**Comment by remlei** [comment]
broken still.... latest version of Edge, tried Chrome same issue. tried firefox. works fine..

maybe try loading more containers on it and see if it breaks, or just wait a little longer. since a fresh install of yacht with nothing installed on it works just fine until you start filling the boat.

**Comment by wickedyoda** [comment]
Honestly I feel sorry for you if you're using edge, That's the most worthless browser there is, it's only got slightly better since they took up Google Chrome's engine. The back end for edge is that of chromium browser the open source version or back end of Google Chrome. I would really say that this is not a yacht issue as much as a Google Chrome issue with HTML5. If you're comparing edge, Chrome, and chromium. They're really the same browser behind the scenes, Firefox is based off of different back end. 

Chrome in general has a lot of compatibility issues with HTML5 documents. I will look tonight at what version of cronium that was in the screenshot and let you know. Maybe you can look for a specific build and use it if it's necessary.

Sorry if the wording sounds a little messed up, I dictate most of my things.

**Comment by SelfhostedPro** [comment]
I have used yacht almost exclusively via chrome since it's creation so I'm unsure if it's chrome specific.

**Comment by wickedyoda** [comment]
I am almost ready to change my opinion there also, I have Chromium 92.0.451 on Debian 11 in the screenshot, Google Chrome ver: 96.0.4664.45, Edge 96.0.1054.29, and Firefox ver: 94.0.2 on my laptop. It's all working on every platform. I wonder if it's a browser plugin, maybe an antivirus plugin.

I would be tempted to use the debugging within Chrome and see what the logs say. https://support.google.com/chrome/a/answer/6271282?hl=en#zippy=%2Cwindows

@SelfhostedPro Thoughts, about this not being a Yacht issue?

**Comment by SelfhostedPro** [comment]
It's possible that it's not but since it's affecting users of Yacht I'd like to try to figure out what's going on so I can at least add a note to the docs. I've been unable to replicate this issue at all unfortunately though. Does the devel branch help at all?

**Comment by wickedyoda** [comment]
I am on Version: v0.0.7-alpha-2021-05-31--16 if that helps.

**Comment by SelfhostedPro** [comment]
@remlei if you get a chance, can you try with Vivaldi? It’s also chromium based. Also, how many containers are you running?

If you have discord, you could send me the support bundle (if you click help from the drop down in the application page on mobile or just the help button on the desktop version). Or feel free to post it here if it doesn’t have any private info. It’s just the output of `docker configure appname` combined with the logs in a zip file.

**Comment by wickedyoda** [comment]
https://discord.gg/MuxjTyuhDA

**Comment by aaemon** [comment]
facing the same issue in brave browser

**Comment by rmatte** [comment]
I see the same thing that's described here in Google Chrome. Several pages will generally only load successfully the first time I open the Yacht site but if I click in to them a second time they never load. This happens on the Templates page and main Dashboard pages most notably but I've seen it on other pages as well. Sometimes closing the entire tab and opening a new one will get the page to load again but sometimes that doesn't even work. Sometimes closing and re-opening the entire browser is required. It's like it's some kind of weird browser state issue or something. This doesn't happen in Firefox, it works flawlessly in that browser but for some reason it currently does not play nicely with Chrome at all.

**Comment by wickedyoda** [comment]
> I see the same thing that's described here in Google Chrome. Several pages will generally only load successfully the first time I open the Yacht site but if I click in to them a second time they never fully load. This happens on the Templates page and main Dashboard pages most notably but I've seen it on other pages as well. Sometimes closing the entire tab and opening a new one will get the page to load again but sometimes that doesn't even work. Sometimes closing and re-opening the entire browser is required. It's like it's some kind of weird browser state issue or something. This doesn't happen in Firefox, it works flawlessly in that browser but for some reason it currently does not play nicely with Chrome at all.

Try rebuilding your container using the :devel tag, it's the most stable one not pushed to production. It's where we have applied some fixes and are testing before going full production. If it works with devel, then it's an issue which has already been addressed.

**Comment by rmatte** [comment]
> > I see the same thing that's described here in Google Chrome. Several pages will generally only load successfully the first time I open the Yacht site but if I click in to them a second time they never fully load. This happens on the Templates page and main Dashboard pages most notably but I've seen it on other pages as well. Sometimes closing the entire tab and opening a new one will get the page to load again but sometimes that doesn't even work. Sometimes closing and re-opening the entire browser is required. It's like it's some kind of weird browser state issue or something. This doesn't happen in Firefox, it works flawlessly in that browser but for some reason it currently does not play nicely with Chrome at all.
> 
> Try rebuilding your container using the :devel tag, it's the most stable one not pushed to production. It's where we have applied some fixes and are testing before going full production. If it works with devel, then it's an issue which has already been addressed.

Thanks, I'll give it a shot.

**Comment by wickedyoda** [comment]
Come join our discord for direct support and work with others. https://discord.gg/JfsebxqKDW

**Comment by rmatte** [comment]
> > I see the same thing that's described here in Google Chrome. Several pages will generally only load successfully the first time I open the Yacht site but if I click in to them a second time they never fully load. This happens on the Templates page and main Dashboard pages most notably but I've seen it on other pages as well. Sometimes closing the entire tab and opening a new one will get the page to load again but sometimes that doesn't even work. Sometimes closing and re-opening the entire browser is required. It's like it's some kind of weird browser state issue or something. This doesn't happen in Firefox, it works flawlessly in that browser but for some reason it currently does not play nicely with Chrome at all.
> 
> Try rebuilding your container using the :devel tag, it's the most stable one not pushed to production. It's where we have applied some fixes and are testing before going full production. If it works with devel, then it's an issue which has already been addressed.

I can confirm that using the devel version in chrome works much much better, haven't noticed any of the problems that I was seeing previously.

**Comment by wickedyoda** [comment]
Thanks, it's possible that the bug has already been addressed in the devel level image. There is some reworking being done to the backend and a big update to come. We don't have a time frame yet.

**Comment by wickedyoda** [comment]
Thanks, it's possible that the bug has already been addressed in the devel level image. There is some reworking being done to the backend and a big update to come. We don't have a time frame yet.

**Comment by LongDono** [comment]
Sadly, this is still broken. I've not been able to get the devel version to work (no response on port 8000). It works to load the initial dashboard and let you get to the admin password change screen, but everything stops responding after that.
